-- ============================================================================
-- SpaceHub schema — Customers · Branches · Spaces · Custom Fields
-- Designed for 350k+ customers with fast server-side search.
-- PostgreSQL 16. Extensions pg_trgm + unaccent are created by the DB bootstrap
-- step (as a superuser); this file assumes they already exist.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;

-- Immutable wrapper around unaccent() so it can be used in expression indexes.
CREATE OR REPLACE FUNCTION f_unaccent(text)
RETURNS text
LANGUAGE sql IMMUTABLE PARALLEL SAFE STRICT
AS $func$ SELECT public.unaccent('public.unaccent'::regdictionary, $1) $func$;

-- Fresh start (dev-friendly). Order matters due to FKs.
DROP TABLE IF EXISTS
  customer_custom_field_values, branch_custom_field_values, space_custom_field_values,
  custom_field_definitions,
  activities, communications, documents, notes, payments, visits, bookings,
  customer_tags, tags, customer_spaces, customer_branches,
  spaces, branches, customers, employees CASCADE;

-- ---------------------------------------------------------------------------
-- Employees (assigned staff)
-- ---------------------------------------------------------------------------
CREATE TABLE employees (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name  TEXT NOT NULL,
  last_name   TEXT NOT NULL,
  full_name   TEXT GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
  email       TEXT,
  role        TEXT,
  avatar_url  TEXT
);

-- ---------------------------------------------------------------------------
-- Branches
-- ---------------------------------------------------------------------------
CREATE TABLE branches (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code          TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  address_line  TEXT,
  city          TEXT,
  area          TEXT,
  postal_code   TEXT,
  phone         TEXT,
  email         TEXT,
  image_url     TEXT,
  lat           DOUBLE PRECISION,
  lng           DOUBLE PRECISION,
  spaces_count  INT NOT NULL DEFAULT 0,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_text   TEXT GENERATED ALWAYS AS (
    coalesce(name,'') || ' ' || coalesce(city,'') || ' ' || coalesce(area,'') || ' ' ||
    coalesce(code,'') || ' ' || coalesce(address_line,'')
  ) STORED
);

-- ---------------------------------------------------------------------------
-- Spaces (belong to a branch)
-- ---------------------------------------------------------------------------
CREATE TABLE spaces (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id     BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  code          TEXT UNIQUE NOT NULL,
  name          TEXT NOT NULL,
  space_type    TEXT,
  capacity      INT,
  floor         TEXT,
  hourly_price  NUMERIC(10,2),
  image_url     TEXT,
  description   TEXT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  search_text   TEXT GENERATED ALWAYS AS (
    coalesce(name,'') || ' ' || coalesce(space_type,'') || ' ' || coalesce(code,'')
  ) STORED
);

-- ---------------------------------------------------------------------------
-- Customers (primary entity)
-- ---------------------------------------------------------------------------
CREATE TABLE customers (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code             TEXT UNIQUE NOT NULL,          -- e.g. C-100245
  first_name       TEXT NOT NULL,
  last_name        TEXT NOT NULL,
  full_name        TEXT GENERATED ALWAYS AS (first_name || ' ' || last_name) STORED,
  email            TEXT,
  phone            TEXT,
  mobile           TEXT,
  company          TEXT,
  tax_id           TEXT,
  customer_type    TEXT NOT NULL DEFAULT 'individual',  -- individual | company
  status           TEXT NOT NULL DEFAULT 'active',      -- active | inactive | prospect
  is_vip           BOOLEAN NOT NULL DEFAULT false,
  date_of_birth    DATE,
  address_line     TEXT,
  city             TEXT,
  postal_code      TEXT,
  country          TEXT DEFAULT 'Ελλάδα',
  avatar_url       TEXT,
  profile_note     TEXT,
  assigned_employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  registered_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  -- Denormalized aggregates for a fast directory (kept in sync at write time).
  branches_count   INT NOT NULL DEFAULT 0,
  spaces_count     INT NOT NULL DEFAULT 0,
  bookings_count   INT NOT NULL DEFAULT 0,
  visits_count     INT NOT NULL DEFAULT 0,
  total_value      NUMERIC(12,2) NOT NULL DEFAULT 0,
  last_visit_at    TIMESTAMPTZ,
  next_booking_at  TIMESTAMPTZ,
  search_text      TEXT GENERATED ALWAYS AS (
    coalesce(first_name,'') || ' ' || coalesce(last_name,'') || ' ' ||
    coalesce(email,'') || ' ' || coalesce(phone,'') || ' ' || coalesce(mobile,'') || ' ' ||
    coalesce(company,'') || ' ' || coalesce(tax_id,'') || ' ' || coalesce(code,'')
  ) STORED
);

-- ---------------------------------------------------------------------------
-- Relationship tables (normalized, many-to-many)
-- ---------------------------------------------------------------------------
CREATE TABLE customer_branches (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  branch_id     BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  is_primary    BOOLEAN NOT NULL DEFAULT false,
  visits_count  INT NOT NULL DEFAULT 0,
  spaces_count  INT NOT NULL DEFAULT 0,
  total_value   NUMERIC(12,2) NOT NULL DEFAULT 0,
  first_visit_at TIMESTAMPTZ,
  last_visit_at TIMESTAMPTZ,
  UNIQUE (customer_id, branch_id)
);

CREATE TABLE customer_spaces (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id   BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  space_id      BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  branch_id     BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  visits_count  INT NOT NULL DEFAULT 0,
  bookings_count INT NOT NULL DEFAULT 0,
  last_visit_at TIMESTAMPTZ,
  UNIQUE (customer_id, space_id)
);

-- ---------------------------------------------------------------------------
-- Tags
-- ---------------------------------------------------------------------------
CREATE TABLE tags (
  id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name   TEXT NOT NULL,
  slug   TEXT UNIQUE NOT NULL,
  color  TEXT NOT NULL DEFAULT 'blue'
);

CREATE TABLE customer_tags (
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  tag_id      BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
  PRIMARY KEY (customer_id, tag_id)
);

-- ---------------------------------------------------------------------------
-- Activity / history tables
-- ---------------------------------------------------------------------------
CREATE TABLE bookings (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id  BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  branch_id    BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  space_id     BIGINT REFERENCES spaces(id) ON DELETE SET NULL,
  employee_id  BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  starts_at    TIMESTAMPTZ NOT NULL,
  ends_at      TIMESTAMPTZ NOT NULL,
  status       TEXT NOT NULL DEFAULT 'confirmed',  -- pending|confirmed|completed|cancelled
  amount       NUMERIC(10,2) NOT NULL DEFAULT 0,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE visits (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id      BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  branch_id        BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  space_id         BIGINT REFERENCES spaces(id) ON DELETE SET NULL,
  visited_at       TIMESTAMPTZ NOT NULL,
  duration_minutes INT,
  visit_type       TEXT NOT NULL DEFAULT 'visit',      -- visit | booking
  status           TEXT NOT NULL DEFAULT 'completed'   -- completed|cancelled|no_show
);

CREATE TABLE payments (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  booking_id  BIGINT REFERENCES bookings(id) ON DELETE SET NULL,
  amount      NUMERIC(10,2) NOT NULL,
  method      TEXT,                 -- card | cash | transfer
  status      TEXT NOT NULL DEFAULT 'paid',
  paid_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE communications (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  channel     TEXT NOT NULL,        -- email | sms | call
  direction   TEXT NOT NULL DEFAULT 'outbound',
  subject     TEXT,
  body        TEXT,
  employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE documents (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  name        TEXT NOT NULL,
  mime_type   TEXT,
  size_bytes  BIGINT,
  url         TEXT,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE notes (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  body        TEXT NOT NULL,
  employee_id BIGINT REFERENCES employees(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE activities (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  type        TEXT NOT NULL,  -- booking_created|booking_completed|payment_received|message_sent|note_added|visit|document_uploaded
  description TEXT,
  branch_id   BIGINT REFERENCES branches(id) ON DELETE SET NULL,
  space_id    BIGINT REFERENCES spaces(id) ON DELETE SET NULL,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ---------------------------------------------------------------------------
-- Dynamic custom fields (typed-value architecture, NOT unindexed EAV/JSON)
-- ---------------------------------------------------------------------------
CREATE TABLE custom_field_definitions (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entity_type   TEXT NOT NULL,     -- customer | branch | space
  name          TEXT NOT NULL,
  key           TEXT NOT NULL,
  field_type    TEXT NOT NULL,     -- text|number|date|boolean|select|multiselect|...
  required      BOOLEAN NOT NULL DEFAULT false,
  searchable    BOOLEAN NOT NULL DEFAULT false,
  filterable    BOOLEAN NOT NULL DEFAULT false,
  visible_in_list BOOLEAN NOT NULL DEFAULT false,
  settings      JSONB NOT NULL DEFAULT '{}'::jsonb,
  section       TEXT,
  sort_order    INT NOT NULL DEFAULT 0,
  active        BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (entity_type, key)
);

CREATE TABLE customer_custom_field_values (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id         BIGINT NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
  field_definition_id BIGINT NOT NULL REFERENCES custom_field_definitions(id) ON DELETE CASCADE,
  text_value          TEXT,
  number_value        NUMERIC,
  date_value          DATE,
  boolean_value       BOOLEAN,
  json_value          JSONB,
  UNIQUE (customer_id, field_definition_id)
);

CREATE TABLE branch_custom_field_values (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  branch_id           BIGINT NOT NULL REFERENCES branches(id) ON DELETE CASCADE,
  field_definition_id BIGINT NOT NULL REFERENCES custom_field_definitions(id) ON DELETE CASCADE,
  text_value          TEXT,
  number_value        NUMERIC,
  date_value          DATE,
  boolean_value       BOOLEAN,
  json_value          JSONB,
  UNIQUE (branch_id, field_definition_id)
);

CREATE TABLE space_custom_field_values (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  space_id            BIGINT NOT NULL REFERENCES spaces(id) ON DELETE CASCADE,
  field_definition_id BIGINT NOT NULL REFERENCES custom_field_definitions(id) ON DELETE CASCADE,
  text_value          TEXT,
  number_value        NUMERIC,
  date_value          DATE,
  boolean_value       BOOLEAN,
  json_value          JSONB,
  UNIQUE (space_id, field_definition_id)
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Customers: smart search (trigram, accent-insensitive) + exact/sort B-trees.
CREATE INDEX idx_customers_search_trgm ON customers USING gin (f_unaccent(lower(search_text)) gin_trgm_ops);
CREATE INDEX idx_customers_fullname_trgm ON customers USING gin (f_unaccent(lower(full_name)) gin_trgm_ops);
CREATE INDEX idx_customers_lastname ON customers (f_unaccent(lower(last_name)) text_pattern_ops);
CREATE INDEX idx_customers_email_lower ON customers (lower(email));
CREATE INDEX idx_customers_phone ON customers (phone);
CREATE INDEX idx_customers_mobile ON customers (mobile);
CREATE INDEX idx_customers_tax_id ON customers (tax_id);
CREATE INDEX idx_customers_status ON customers (status);
CREATE INDEX idx_customers_type ON customers (customer_type);
CREATE INDEX idx_customers_vip ON customers (is_vip) WHERE is_vip;
CREATE INDEX idx_customers_created_at ON customers (created_at);
CREATE INDEX idx_customers_city ON customers (f_unaccent(lower(city)));
-- Keyset pagination sort keys (value, id) to keep deep pages fast.
CREATE INDEX idx_customers_lastvisit_keyset ON customers ((COALESCE(last_visit_at, to_timestamp(0))) DESC, id DESC);
CREATE INDEX idx_customers_value_keyset ON customers (total_value DESC, id DESC);
CREATE INDEX idx_customers_name_keyset ON customers (f_unaccent(lower(full_name)) ASC, id ASC);
CREATE INDEX idx_customers_created_keyset ON customers (created_at DESC, id DESC);

-- Branches / Spaces search.
CREATE INDEX idx_branches_search_trgm ON branches USING gin (f_unaccent(lower(search_text)) gin_trgm_ops);
CREATE INDEX idx_branches_city ON branches (f_unaccent(lower(city)));
CREATE INDEX idx_spaces_search_trgm ON spaces USING gin (f_unaccent(lower(search_text)) gin_trgm_ops);
CREATE INDEX idx_spaces_branch ON spaces (branch_id);
CREATE INDEX idx_spaces_type ON spaces (f_unaccent(lower(space_type)));

-- Relationship tables (both directions for relationship filters).
CREATE INDEX idx_cb_customer ON customer_branches (customer_id);
CREATE INDEX idx_cb_branch ON customer_branches (branch_id);
CREATE INDEX idx_cs_customer ON customer_spaces (customer_id);
CREATE INDEX idx_cs_space ON customer_spaces (space_id);
CREATE INDEX idx_cs_branch ON customer_spaces (branch_id);

-- History tables (customer-scoped, time-ordered).
CREATE INDEX idx_bookings_customer_time ON bookings (customer_id, starts_at DESC);
CREATE INDEX idx_bookings_space ON bookings (space_id);
CREATE INDEX idx_visits_customer_time ON visits (customer_id, visited_at DESC);
CREATE INDEX idx_visits_space ON visits (space_id);
CREATE INDEX idx_payments_customer_time ON payments (customer_id, paid_at DESC);
CREATE INDEX idx_communications_customer_time ON communications (customer_id, created_at DESC);
CREATE INDEX idx_documents_customer_time ON documents (customer_id, created_at DESC);
CREATE INDEX idx_notes_customer_time ON notes (customer_id, created_at DESC);
CREATE INDEX idx_activities_customer_time ON activities (customer_id, created_at DESC);
CREATE INDEX idx_customer_tags_tag ON customer_tags (tag_id);

-- Custom fields.
CREATE INDEX idx_cfd_entity ON custom_field_definitions (entity_type, active, sort_order);
CREATE INDEX idx_ccfv_customer ON customer_custom_field_values (customer_id);
CREATE INDEX idx_ccfv_field_text ON customer_custom_field_values (field_definition_id, text_value);
CREATE INDEX idx_ccfv_field_num ON customer_custom_field_values (field_definition_id, number_value);
CREATE INDEX idx_ccfv_text_trgm ON customer_custom_field_values USING gin (f_unaccent(lower(text_value)) gin_trgm_ops);
