// Mirror of the backend permission codes (see backend/src/lib/permissions.js).
export const PERMS = {
  CUSTOMERS_READ: 'customers.read',
  CUSTOMERS_WRITE: 'customers.write',
  CUSTOMERS_DELETE: 'customers.delete',
  CUSTOMERS_EXPORT: 'customers.export',
  BRANCHES_READ: 'branches.read',
  SPACES_READ: 'spaces.read',
  REPORTS_READ: 'reports.read',
  SETTINGS_MANAGE: 'settings.manage',
  USERS_MANAGE: 'users.manage',
  ROLES_MANAGE: 'roles.manage',
  TENANT_MANAGE: 'tenant.manage',
  TENANTS_PLATFORM: 'tenants.platform',
  QUOTES_VIEW: 'quotes.view',
  QUOTES_CREATE: 'quotes.create',
  QUOTES_EDIT: 'quotes.edit',
  QUOTES_SEND_EMAIL: 'quotes.send_email',
  QUOTES_FETCH_LINES: 'quotes.fetch_lines',
  BOOKINGS_VIEW: 'bookings.view',
  BOOKINGS_CREATE: 'bookings.create',
  BOOKINGS_EDIT: 'bookings.edit',
  BOOKINGS_DELETE: 'bookings.delete',
};
